### ISSUE TITLE
Exception when running octopress ink list with date-format installed

### ISSUE THREAD

**Issue by drallgood** [octopress/date-format#5]
I get this exception
```
$ bundle exec octopress ink list -t
/Library/Ruby/Gems/2.0.0/gems/octopress-date-format-3.0.2/lib/octopress-date-format.rb:78:in `format_date': undefined method `[]' for nil:NilClass (NoMethodError)
```
Looks like it can't find the date_format key in the config, which is weird because it is in my `_confg.yml`
```
date_format: "ordinal"
```
Ideas?

**Comment by imathis** [comment]
I'm trying to figure out why this is happening. The code on line 78 should only be executed when you're building the site. If you comment out everything except `octopress-date-format` does it still happen?

**Comment by drallgood** [comment]
Nope.

It only happens in conjunction with the asset pipeline plugin.

**Comment by imathis** [comment]
Excellent. Now we're getting somewhere. Thanks!

**Comment by imathis** [comment]
Grr! I can't seem to replicate this. My Gemfile looks like this:

```ruby
group :jekyll_plugins do
  gem 'octopress-date-format'
  gem 'octopress-asset-pipeline'
end
```

And I'm running `bundle exec octopress ink list` from my site root. Anything else I can do?

**Comment by drallgood** [comment]
hmm.. Weird.

After creating a fresh Gemfile this issue disappeared. 

Thanks for your help!
